Fixed Issue #1314 Formatting done- Section 6.9.3
mschermann/data_viz_reader pull request #1350
Opened 2019-06-02 05:00 UTC by AayushiVAgrawal

2019-06-02 22:03 UTC, rlwy commented on .idea/data_viz_reader.iml
> +<?xml version="1.0" encoding="UTF-8"?>
What does this file do?

2019-06-03 04:15 UTC, pragyansharma24 approved these changes

2019-06-03 04:19 UTC, pragyansharma24 commented on 06-process.Rmd
> +3.   **Lack of Guidance:** It is possible that the user who is interpreting the data lacks training. This can have huge impact on the company. At the same time, analysts could provide clients with in
The answer is so simple that **it is** easy to miss.

2019-06-03 04:23 UTC, pragyansharma24 requested changes
Hi Aayushi, 
Please check if this file was committed knowingly or by mistake.

2019-06-03 16:36 UTC, mschermann commented
@AayushiVAgrawal What is the status here?

2019-06-10 17:56 UTC, mschermann commented
@AayushiVAgrawal Why is this still open? Please fix and close.

2019-06-10 18:04 UTC, merged

2019-06-10 22:37 UTC, AayushiVAgrawal commented
Closed issue #1314