Further Introduction updates Issue #1229
mschermann/data_viz_reader pull request #1362
Opened 2019-06-02 22:06 UTC by kwright76

Added to the introduction to include some of the topics and specific use cases that my class mates have added.

2019-06-03 05:19 UTC, syragrg requested changes
Hi Kyle just some minor grammatical and spelling issues need to be fixed @ third and second last sentence! other than that, great addition to help with the flow of the chapter!

2019-06-03 05:19 UTC, syragrg commented on 06-process.Rmd
> +In each data visualization project there are many things to consider to minimize risk and ensure a successful project. This chapter will explain many of these concepts along with some use cases that
did you mean data at the third sentence?

2019-06-03 05:19 UTC, syragrg commented on 06-process.Rmd
> +In each data visualization project there are many things to consider to minimize risk and ensure a successful project. This chapter will explain many of these concepts along with some use cases that
could you put a comma after 'For example' and Altair @ second last sentence

2019-06-03 16:33 UTC, mschermann commented
@kwright76 Please respond to reviews and merge.

2019-06-04 00:52 UTC, kwright76 commented
Hi @syragrg, I went ahead and made the corrections. Thanks for the review!

2019-06-04 01:13 UTC, syragrg approved these changes
thank you Kyle!

2019-06-04 01:13 UTC, merged